/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: kiria_d (https://sketchfab.com/kirilldrac78)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/air-force1-9497c5d927b04f2281e86a0777784177
Title: Air Force1
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[8.71, 23.11, -11.17]} rotation={[-Math.PI / 2, 0, -0.08]} scale={18.64}>
          <mesh geometry={nodes.Plane_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Plane_Material006_0.geometry} material={materials['Material.006']} />
          <mesh geometry={nodes.Plane_Material010_0.geometry} material={materials['Material.010']} />
          <mesh geometry={nodes.Plane_Material002_0.geometry} material={materials['Material.002']} />
        </group>
        <group position={[34.9, 98.99, -9.36]} rotation={[0, -0.02, 0]} scale={8.81}>
          <mesh geometry={nodes.Plane001_Fine_leather_black_0.geometry} material={materials.Fine_leather_black} />
          <mesh geometry={nodes.Plane001_Fabric_0.geometry} material={materials.Fabric} />
        </group>
        <group position={[-14.99, 110.11, -10.76]} rotation={[-Math.PI / 2, 0, -0.02]} scale={100}>
          <mesh geometry={nodes.Plane002_Hex_fabric_Cloth_0.geometry} material={materials.Hex_fabric_Cloth} />
          <mesh geometry={nodes.Plane002_Degradable_Metal_0.geometry} material={materials.Degradable_Metal} />
          <mesh geometry={nodes.Plane002_Metal_0.geometry} material={materials.Metal} />
        </group>
        <mesh geometry={nodes.Plane003__0.geometry} material={materials['Plane.003__0']} position={[-0.43, 36.88, -10.69]} rotation={[-Math.PI / 2, 0, -0.02]} scale={100} />
        <mesh geometry={nodes.Plane004_Fabric_Pattern_06_0.geometry} material={materials.Fabric_Pattern_06} position={[151.31, 113.73, -7.35]} rotation={[0, 1.55, 0]} scale={0.38} />
        <mesh geometry={nodes.Plane005_Material004_0.geometry} material={materials['Material.004']} position={[-9.47, 67.36, 35.6]} rotation={[0, -0.02, -1.1]} scale={[1.15, 0.2, 1.15]} />
        <mesh geometry={nodes.Plane006_Material004_0.geometry} material={materials['Material.004']} position={[-98.33, 63.47, -9.95]} rotation={[0, -0.02, -1.1]} scale={[1.15, 0.2, 1.15]} />
        <mesh geometry={nodes.Plane007_Material004_0.geometry} material={materials['Material.004']} position={[-10.82, 62.9, -50.88]} rotation={[Math.PI, 0.02, 2.04]} scale={[1.15, 0.2, 1.15]} />
        <mesh geometry={nodes.Plane008_Material004_0.geometry} material={materials['Material.004']} position={[69.04, 88.37, 36.09]} rotation={[0, -0.02, -1.1]} scale={[1.15, 0.2, 1.15]} />
        <mesh geometry={nodes.Plane009_Material004_0.geometry} material={materials['Material.004']} position={[67.48, 81.75, -51.34]} rotation={[Math.PI, 0.02, 2.04]} scale={[1.15, 0.2, 1.15]} />
        <mesh geometry={nodes.Plane010_Material004_0.geometry} material={materials['Material.004']} position={[-20.93, 101.62, -40.31]} rotation={[-Math.PI, 0.02, 0.76]} scale={[1.15, 0.2, 1.15]} />
        <mesh geometry={nodes.Plane011_Material004_0.geometry} material={materials['Material.004']} position={[160.17, 97.11, -10.62]} rotation={[-Math.PI, 0.02, 0.76]} scale={[1.15, 0.2, 1.15]} />
        <mesh geometry={nodes.Plane012_Material004_0.geometry} material={materials['Material.004']} position={[-18.2, 102.86, 20.81]} rotation={[0, -0.02, 2.38]} scale={[-1.15, 0.2, 1.15]} />
        <mesh geometry={nodes.Plane013_Material004_0.geometry} material={materials['Material.004']} position={[73.54, 87.74, 37.24]} rotation={[0, -0.02, 0.56]} scale={[-1.15, 0.2, 1.15]} />
        <mesh geometry={nodes.Plane014_Material004_0.geometry} material={materials['Material.004']} position={[69.35, 89.76, -53.43]} rotation={[Math.PI, 0.02, 2.58]} scale={[1.15, 0.2, 1.15]} />
        <mesh geometry={nodes.Plane019_Fabric_Pattern_06_0.geometry} material={materials.Fabric_Pattern_06} position={[150.41, 113.73, -189.93]} rotation={[0, 1.46, 0]} scale={[-0.38, 0.38, 0.38]} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
